#phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    container_name: phpmyadmin
 #  environment:
#     - PMA_ARBITRARY=1
 #   restart: always
 #   ports:
 #    - 9191:80
 #   volumes:
  #   - /sessions

version: '3.1'  

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment: 
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: example
      PMA_USER: user
      PMA_PASSWORD: anas123
    restart: always
    ports:
      - "9191:80"
    volumes:
      - /sessions
